# For documentation on how to configure this file,
# see diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "strategies/src/sql_schema.rs"
import_types = ["diesel::sql_types::*", "crate::order_types::*"]   # <- note the extra import
