[target.x86_64-unknown-linux-gnu]
#linker="clang"
## debug
rustflags = [
    "-Clink-arg=-Wl,--allow-multiple-definition", "-Clink-arg=-fPIC"
]

[build]
rustflags = ["-Clink-arg=-Wl,--allow-multiple-definition", "-Clink-arg=-fPIC"]
