exchanges:
  #  Bitstamp:
  #    orderbook:
  #      symbols: ['BTC_USD']
  #      trades:
  #        symbols: ['BTC_USD']
  binance:
    orderbook:
      symbols: ['BTC_USDT', 'BCH_USDT', 'ETH_USDT', 'ETC_USDT', 'XRP_USDT', 'EOS_USDT', 'BNB_USDT', 'LTC_USDT', 'DASH_USDT', 'BAB_USD', 'ETC_USD', 'BTC_USD', 'ETH_USD', 'BSV_USD', 'USDT_USD', 'XRP_USD', 'LTC_USD', 'EOS_USD', 'ETH_BTC', 'BCH_BTC', 'ETC_BTC', 'XRP_BTC', 'BSV_BTC', 'XTP_BTC', 'XRP_BTC', 'ADA_BTC', 'TUSD_BTC', 'STEEM_BTC', 'LTC_BTC', 'ZEC_BTC', 'BTC_EUR', 'ETH_EUR']
    trades:
      symbols: ['BTC_USDT', 'BCH_USDT', 'ETH_USDT', 'ETC_USDT', 'XRP_USDT', 'EOS_USDT', 'BNB_USDT', 'LTC_USDT', 'DASH_USDT', 'BAB_USD', 'ETC_USD', 'BTC_USD', 'ETH_USD', 'BSV_USD', 'USDT_USD', 'XRP_USD', 'LTC_USD', 'EOS_USD', 'ETH_BTC', 'BCH_BTC', 'ETC_BTC', 'XRP_BTC', 'BSV_BTC', 'XTP_BTC', 'XRP_BTC', 'ADA_BTC', 'TUSD_BTC', 'STEEM_BTC', 'LTC_BTC', 'ZEC_BTC', 'BTC_EUR', 'ETH_EUR']

strategies:
  - type: Naive
    left: 'ETH_USDT'
    right: 'BTC_USDT'
    exchange: Binance
    beta_eval_freq: 5000
    beta_sample_freq: 1min
    window_size: 500

file_rotation:
  max_file_size: 50 Mb
  max_file_time: 1800

data_dir: './data'

keys: /root/config/keys_real.json

db_storage_path: './database'

prom_push_gw: 127.0.0.1:9091
