exchanges:
  #  Bitstamp:
  #    orderbook:
  #      symbols: ['BTC_USD']
  #      trades:
  #        symbols: ['BTC_USD']
  binance:
    fees: 0.001
    use_account: true
    use_test: false
    orderbook_depth: 5
    orderbook:
      symbols: ['.*_USDT']

streams:
  - type: ExchangeBots

outputs:
  - type: AvroFileLogger
    file_rotation:
      max_file_size: 50 Mb
      max_file_time: 36000
    basedir: './data24'
    partitions_grace_period: 1mn

data_dir: './data24'

keys: /root/config/keys_real.json

db_storage_path: './database'

prometheus:
  push_gateway: 127.0.0.1:9091
  instance: feeder24


api:
  port: 8184
