exchanges:
  #  Bitstamp:
  #    orderbook:
  #      symbols: ['BTC_USD']
  #      trades:
  #        symbols: ['BTC_USD']
  binance:
    fees: 0.001
    use_account: true
    use_test: false
    orderbook_depth: 5
    orderbook:
      symbols: ['BTC_USDT', 'BCH_USDT', 'ETH_USDT', 'ETC_USDT', 'XRP_USDT', 'EOS_USDT', 'BNB_USDT', 'LTC_USDT', 'DASH_USDT', 'ETH_BTC', 'BCH_BTC', 'ETC_BTC', 'ADA_BTC', 'BTC_TUSD', 'STEEM_BTC', 'LTC_BTC', 'ZEC_BTC', 'BTC_EUR', 'ETH_EUR']
    trades:
      symbols: ['BTC_USDT', 'BCH_USDT', 'ETH_USDT', 'ETC_USDT', 'XRP_USDT', 'EOS_USDT', 'BNB_USDT', 'LTC_USDT', 'DASH_USDT', 'ETH_BTC', 'BCH_BTC', 'ETC_BTC', 'ADA_BTC', 'BTC_TUSD', 'STEEM_BTC', 'LTC_BTC', 'ZEC_BTC', 'BTC_EUR', 'ETH_EUR']

streams:
  - type: ExchangeBots

outputs:
  - type: AvroFileLogger
    file_rotation:
      max_file_size: 50 Mb
      max_file_time: 1800
    basedir: './data'
    partitions_grace_period: 1mn

data_dir: './data'

keys: /root/config/keys_real.json

db_storage_path: './database'

prometheus:
  push_gateway: 127.0.0.1:9091
  instance: feeder


api:
  port: 8181
