exchanges:
  binance:
    use_account: true
    use_test: false
    fees: 0.001

balance_reporter:
  refresh_rate: 10s

keys: /root/config/portfolio_keys.json

storage:
  path: './database_portfolio'
  engine:
    type: rocks_db

prometheus:
  push_gateway: 127.0.0.1:9091
  instance: balance_reporter

api:
  port: 0
