exchanges:
  binance:
    fees: 0.001
    use_account: true
    use_test: false
    orderbook_depth: 5
    orderbook:
      symbols: [ '.*(?<!LTC|BTC|ETC|UP|DOWN)_USDT' ]

streams:
  - type: ExchangeBots

outputs:
  - type: Strategies

strategies_copy:
  - type: mean_reverting
    pairs: [ '.*(?<!LTC|BTC|ETC|UP|DOWN)_USDT' ]
    base:
      pair: ''
      short_window_size: 100
      long_window_size: 1000
      dry_mode: true
      sample_freq: 1min
      initial_cap: 100.0
      threshold_short: 0.02
      threshold_long: -0.02
      threshold_eval_freq: 1
      dynamic_threshold: true
      threshold_window_size: 1000
      stop_loss: -0.1
      stop_gain: 0.075
      exchange: Binance
      order_mode: limit

strategies: []

keys: /root/config/keys_real.json

db:
  path: './database_dry'
  engine:
    type: rocksdb

prometheus:
  push_gateway: 127.0.0.1:9091
  instance: trader_dry

api:
  port: 8187
