exchanges:
  binance:
    fees: 0.001
    use_account: true
    use_margin_account: true
    use_test: false
    orderbook_depth: 5
    orderbook:
      symbols: [ 'ARPA_USDT' ]

streams:
  - type: ExchangeBots

outputs:
  - type: Strategies

strategies:
  - type: mean_reverting
    pair: 'ARPA_USDT'
    short_window_size: 100
    long_window_size: 1000
    dry_mode: false
    sample_freq: 1min
    initial_cap: 100.0
    threshold_short: 0.01
    threshold_long: -0.01
    threshold_eval_freq: 1
    dynamic_threshold: true
    threshold_window_size: 1000
    stop_loss: -0.1
    stop_gain: 0.075
    exchange: Binance
    order_mode: market
    order_asset_type: margin

keys: /root/config/margin_keys_real.json

storage:
  path: './database_margin'
  engine:
    type: rocks_db

prometheus:
  push_gateway: 127.0.0.1:9091
  instance: trader_margin

balance_reporter:
  refresh_rate: 10s

margin_account_reporter:
  refresh_rate: 10s

api:
  port: 8188
  allowed_origins:
    - "http://10.104.0.3:3001"
    - "http://localhost:3001"
    - "http://10.104.0.2:8188"
