exchanges:
  binance:
    fees: 0.001
    use_account: true
    use_margin_account: true
    use_test: false
    orderbook_depth: 5
    orderbook:
      symbols: [ '.*(?<!LTC|BTC|ETC|UP|DOWN|BEAR|BULL)_USDT' ]

streams:
  - type: ExchangeBots

outputs:
  - type: Strategies

strategies:
  - type: mean_reverting
    pair: 'BTC_USDT'
    short_window_size: 100
    long_window_size: 1000
    dry_mode: true
    sample_freq: 1min
    initial_cap: 100.0
    threshold_short: 0.02
    threshold_long: -0.02
    threshold_eval_freq: 1
    dynamic_threshold: true
    threshold_window_size: 1000
    stop_loss: -0.1
    stop_gain: 0.075
    exchange: Binance
    order_mode: limit
  - type: mean_reverting
    pair: 'LTC_USDT'
    short_window_size: 100
    long_window_size: 1000
    dry_mode: true
    sample_freq: 1min
    initial_cap: 100.0
    threshold_short: 0.02
    threshold_long: -0.02
    threshold_eval_freq: 1
    dynamic_threshold: true
    threshold_window_size: 1000
    stop_loss: -0.1
    stop_gain: 0.075
    exchange: Binance
    order_mode: limit
  - type: mean_reverting
    pair: 'ETC_USDT'
    short_window_size: 100
    long_window_size: 1000
    dry_mode: true
    sample_freq: 1min
    initial_cap: 100.0
    threshold_short: 0.02
    threshold_long: -0.02
    threshold_eval_freq: 1
    dynamic_threshold: true
    threshold_window_size: 1000
    stop_loss: -0.1
    stop_gain: 0.075
    exchange: Binance
    order_mode: limit
  - type: mean_reverting
    pair: 'FIS_USDT'
    short_window_size: 100
    long_window_size: 1000
    dry_mode: true
    sample_freq: 1min
    initial_cap: 100.0
    threshold_short: 0.02
    threshold_long: -0.02
    threshold_eval_freq: 1
    dynamic_threshold: true
    threshold_window_size: 1000
    stop_loss: -0.1
    stop_gain: 0.075
    exchange: Binance
    order_mode: limit
  - type: mean_reverting
    pair: 'BURGER_USDT'
    short_window_size: 100
    long_window_size: 1000
    dry_mode: true
    sample_freq: 1min
    initial_cap: 100.0
    threshold_short: 0.02
    threshold_long: -0.02
    threshold_eval_freq: 1
    dynamic_threshold: true
    threshold_window_size: 1000
    stop_loss: -0.1
    stop_gain: 0.075
    exchange: Binance
    order_mode: limit
  - type: mean_reverting
    pair: 'VITE_USDT'
    short_window_size: 100
    long_window_size: 1000
    dry_mode: true
    sample_freq: 1min
    initial_cap: 100.0
    threshold_short: 0.02
    threshold_long: -0.02
    threshold_eval_freq: 1
    dynamic_threshold: true
    threshold_window_size: 1000
    stop_loss: -0.1
    stop_gain: 0.075
    exchange: Binance
    order_mode: limit
  - type: mean_reverting
    pair: 'BAKE_USDT'
    short_window_size: 100
    long_window_size: 1000
    dry_mode: true
    sample_freq: 1min
    initial_cap: 100.0
    threshold_short: 0.02
    threshold_long: -0.02
    threshold_eval_freq: 1
    dynamic_threshold: true
    threshold_window_size: 1000
    stop_loss: -0.1
    stop_gain: 0.075
    exchange: Binance
    order_mode: limit

#strategies_copy:
#  - type: mean_reverting
#    pairs: [ '.*(?<!LTC|BTC|ETC|UP|DOWN)_USDT' ]
#    base:
#      pair: ''
#      short_window_size: 100
#      long_window_size: 1000
#      dry_mode: true
#      sample_freq: 1min
#      initial_cap: 100.0
#      threshold_short: 0.02
#      threshold_long: -0.02
#      threshold_eval_freq: 1
#      dynamic_threshold: true
#      threshold_window_size: 1000
#      stop_loss: -0.1
#      stop_gain: 0.075
#      exchange: Binance
#      order_mode: limit

keys: /root/config/keys_real.json

storage:
  path: './database_dry'
  engine:
    type: rocks_db

prometheus:
  push_gateway: 127.0.0.1:9091
  instance: trader_dry

api:
  port: 8187
  allowed_origins:
    - "http://10.104.0.3:3001"
    - "http://localhost:3001"
