exchanges:
  #  Bitstamp:
  #    orderbook:
  #      symbols: ['BTC_USD']
  #      trades:
  #        symbols: ['BTC_USD']
  binance:
    fees: 0.001
    use_account: true
    use_test: false
    orderbook_depth: 5
    orderbook:
      symbols: ['BTC_USDT', 'LTC_USDT', 'ETC_USDT']

streams:
  - type: ExchangeBots

outputs:
  - type: Strategies

strategies:
  - type: MeanReverting
    pair: 'BTC_USDT'
    short_window_size: 100
    long_window_size: 1000
    dry_mode: false
    sample_freq: 1min
    initial_cap: 100.0
    threshold_short: 0.01
    threshold_long: -0.01
    threshold_eval_freq: 1
    dynamic_threshold: true
    threshold_window_size: 10000
    stop_loss: -0.1
    stop_gain: 0.075
    exchange: Binance
  - type: MeanReverting
    pair: 'LTC_USDT'
    short_window_size: 100
    long_window_size: 1000
    dry_mode: false
    sample_freq: 1min
    initial_cap: 100.0
    threshold_short: 0.01
    threshold_long: -0.01
    threshold_eval_freq: 1
    dynamic_threshold: true
    threshold_window_size: 10000
    stop_loss: -0.1
    stop_gain: 0.075
    exchange: Binance
  - type: MeanReverting
    pair: 'ETC_USDT'
    short_window_size: 100
    long_window_size: 1000
    dry_mode: false
    sample_freq: 1min
    initial_cap: 100.0
    threshold_short: 0.01
    threshold_long: -0.01
    threshold_eval_freq: 1
    dynamic_threshold: true
    threshold_window_size: 10000
    stop_loss: -0.1
    stop_gain: 0.075
    exchange: Binance

data_dir: './data'

keys: /root/config/keys_real.json

db_storage_path: './database'

prom_push_gw: 127.0.0.1:9091

prom_instance: trader

api:
  port: 8180
