cargo-features = ["edition2021"]

[package]
name = "portfolio"
version = "0.1.0"
authors = ["Guillaume Balaine <igosuki@gmail.com>"]
edition = "2018"

[lib]
name = "portfolio"
path = "src/lib.rs"

[dependencies]
# actix
actix = "0.12"
actix_derive = "0.6"
anyhow = "1.0"
chrono = "0.4"
# Crypto
#coinnect_rt = { git = " ssh://git@github.com/Igosuki/coinnect_rt.git" }
coinnect_rt = { path = "../coinnect" }
prometheus = "0.12"
serde = "1.0"

thiserror = "1.0"
# core
util = { path = "../util" }
log = "0.4"
futures = "0.3"

[dev-dependencies]
