[package]
name = "util"
version = "0.1.0"
authors = ["Guillaume Balaine <igosuki@gmail.com>"]
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
opentelemetry = { version = "0.15", default-features = false, features = ["trace"] }
opentelemetry-jaeger = "0.14"
parse_duration = "2.1"
rust_decimal = "1.11"
serde = "1.0"
serde_json = "1.0"
tempdir = "0.3"
tokio = { version = "1", features = ["full"], optional = true }
byte-unit = "4.0"
mock_instant = "0.2.1"
# Tracing
tracing = { version = "0.1", features = ["release_max_level_debug", "log"] }
tracing-flame = "0.1"
tracing-futures = "0.2"
tracing-log = { version = "0.1", features = ["env_logger"] }
tracing-opentelemetry = "0.14"
tracing-subscriber = { version = "0.2", features = ["tracing-log", "env-filter"] }
tracing-timing = "0.5"

[features]
mock_time = []

[dev-dependencies]

