[package]
name = "util"
version = "0.1.0"
authors = ["Guillaume Balaine <igosuki@gmail.com>"]
edition = "2018"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
opentelemetry = { version = "0.14", default-features = false, features = ["trace"] }
opentelemetry-jaeger = "0.13"
parse_duration = "2.1"
rust_decimal = "1.11"
serde = "1"
tempdir = "0.3"
tokio = { version = "1.5", features = ["full"], optional = true }

# Tracing
tracing = "0.1"
tracing-flame = "0.1"
tracing-futures = "0.2"
tracing-log = { version = "0.1", features = ["env_logger"] }
tracing-opentelemetry = "0.13"
tracing-subscriber = { version = "0.2", features = ["tracing-log", "env-filter"] }
tracing-timing = "0.5"

[features]

[dev-dependencies]
