[package]
name = "util"
version = "0.1.0"
authors = ["Guillaume Balaine <igosuki@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
rusoto_core = { version = "0.44", optional = true }
rusoto_s3 = { version = "0.44", optional = true }
rusoto_credential = { version = "0.44", optional = true }
tokio = { version = "0.2", features = ["full"], optional = true }
serde = "1.0"
rust_decimal = "1.4"

[features]
s3 = ["tokio", "rusoto_core", "rusoto_s3", "rusoto_credential"]

[dev-dependencies]
