[package]
name = "util"
version = "0.1.0"
authors = ["Guillaume Balaine <igosuki@gmail.com>"]
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# std
chrono = { version = "0.4", features = ["serde"] }
parse_duration = "2.1"
rust_decimal = "1.11"
tempdir = "0.3"
byte-unit = "4.0"
hdrhistogram = "7.4"
mock_instant = "0.2.1"
maplit = "1.0"

# serde
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# async
tokio = { version = "1", features = ["full"] }
tokio-stream = { version = "0.1", features = ["sync", "fs", "net", "io-util", "tokio-util", "signal", "time"] }
futures = "0.3"

# Tracing / Logging
pretty_env_logger = "0.4"
opentelemetry = { version = "0.15", default-features = false, features = ["trace"] }
opentelemetry-jaeger = "0.14"
tracing = { version = "0.1", features = ["release_max_level_debug", "log"] }
tracing-flame = "0.1"
tracing-log = { version = "0.1", features = ["env_logger"] }
tracing-opentelemetry = "0.14"
tracing-subscriber = { version = "0.2", features = ["tracing-log", "env-filter"] }
tracing-timing = "0.5"

[features]
mock_time = []

[dev-dependencies]
async-stream = "0.3"
