[package]
name = "backtest"
version = "0.1.0"
edition = "2021"

[lib]
name = "backtest"
path = "src/lib.rs"

[[bin]]
name = "backtest"
path = "src/main.rs"
required-features = ["binary"]

[features]
mock_time = ["util/mock_time"]
binary = ["env_logger", "structopt"]
[dependencies]
# trader
strategies = { path = "../strategies" }
util = { path = "../util" }
ext = { path = "../ext" }
db = { path = "../db" }
stats = { path = "../stats" }
trading = { path = "../trading", features = ["test_util"] }

# async
futures = "0.3"
tokio = "1"
actix = "0.12"

# std
tracing = { version = "0.1", features = ["release_max_level_debug", "log"] }
structopt = { version = "0.3", optional = true }
config = { version = "0.11", features = ["yaml", "toml", "json"], default-features = false }
thiserror = "1.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
parse_duration = "2.1"
env_logger = { version = "0.9", optional = true }
typed-builder = "0.9"
async-trait = "0.1"
itertools = "0.10"
# data
datafusion = { git = "https://github.com/Igosuki/arrow-datafusion", branch = "optional_crates", version = "6.0", default-features = false, features = ["avro", "crypto_expressions", "regex_expressions", "unicode_expressions"] }
#datafusion = { path = "/home/geps/dev/oss/arrow-datafusion/datafusion", version = "5.1", default-features = false, features = ["avro"] }
plotly = { version = "0.6.0", features = ["kaleido"] }
