[package]
name = "backtest"
version = "0.1.0"
edition = "2021"

[lib]
name = "backtest"
path = "src/lib.rs"

[[bin]]
name = "backtest"
path = "src/main.rs"
required-features = ["binary"]

[[bin]]
name = "backtest_data_server"
path = "src/data_server.rs"
required-features = ["binary"]

[features]
default = ["env_logger", "mock_time", "binary"]
mock_time = ["util/mock_time"]
console = ["util/console_tracing"]
release_max_level_debug = ["util/release_max_level_debug", "tracing/release_max_level_debug"]
release_max_level_trace = ["util/release_max_level_trace", "tracing/release_max_level_trace"]
binary = ["env_logger", "structopt"]
release_default = ["mock_time", "binary", "release_max_level_trace"]
remote_execution = ["ballista"]
standalone_execution = ["ballista", "ballista/standalone"]

[dependencies]
# trader
strategy = { path = "../strategy" }
strategies = { path = "../strategies" }
strategy_python = { path = "../strategy_python" }
brokers = { path = "../broker" }

util = { path = "../util" }
ext = { path = "../ext" }
db = { path = "../db" }
stats = { path = "../stats" }
trading = { path = "../trading", features = ["test_util"] }

# async
futures = "0.3"
tokio = "1"
tokio-util = "0.6"
pyo3-asyncio = { version = "0.15", features = ["attributes", "tokio-runtime"] }
async-trait = "0.1"
async-stream = "0.3"
tokio-stream = { version = "0.1", features = ["sync", "fs", "net", "io-util", "tokio-util", "signal", "time"] }

# actors
actix = "0.12"

# cli
structopt = { version = "0.3", optional = true }
config = { version = "0.11", features = ["yaml", "toml", "json"], default-features = false }

# logging / monitoring / metrics
tracing = { version = "0.1", features = ["log"] }

# std
thiserror = "1.0"
anyhow = "1.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
parse_duration = "2.1"
env_logger = { version = "0.9", optional = true }
typed-builder = "0.9"
itertools = "0.10"
hdrhistogram = "7.4"
dashmap = "5"
float-cmp = "0.9"
num_cpus = "1.13"

# datafusion
datafusion = { version = "6.0.0", features = ["avro-schema", "avro", "crypto_expressions", "regex_expressions", "unicode_expressions"] }
ballista = { version = "0.6.0", optional = true }

# reporting
plotly = { version = "0.7", features = ["kaleido"] }
