[package]
name = "backtest"
version = "0.1.0"
edition = "2021"

[lib]
name = "backtest"
path = "src/lib.rs"

[[bin]]
name = "backtest"
path = "src/main.rs"
required-features = ["env_logger"]

[features]
mock_time = ["util/mock_time"]

[dependencies]
# trader
strategies = { path = "../strategies" }
util = { path = "../util" }
ext = { path = "../ext" }

# async
futures = "0.3"
tokio = "1"
actix = "0.12"

# std
log = "0.4"
structopt = "0.3"
config = { version = "0.11", features = ["yaml", "toml", "json"], default-features = false }
thiserror = "1.0"
serde = "1.0"
serde_derive = "1.0"
serde_yaml = "0.8"
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
parse_duration = "2.1"
env_logger = { version = "0.9", optional = true }
typed-builder = "0.9"
async-trait = "0.1"
# data
datafusion = { git = "https://github.com/Igosuki/arrow-datafusion", branch = "map_access_i_optional_features", version = "5.1", default-features = false, features = ["avro"] }
#datafusion = { path = "/home/geps/dev/oss/arrow-datafusion/datafusion", version = "5.1", default-features = false, features = ["avro"] }
