exchanges:
  binance:
    use_account: true
    use_test: true
    fees: 0.001

balance_reporter:
  refresh_rate: 10s

keys: ./config/keys_real_test.json

db:
  path: './database'
  engine:
    type: rocksdb

prometheus:
  push_gateway: 127.0.0.1:9091
  instance: balance_reporter

api:
  port: 0
