exchanges:
  binance:
    use_account: true
    use_margin_account: true
    use_test: true
    fees: 0.001

balance_reporter:
  refresh_rate: 10s

margin_account_reporter:
  refresh_rate: 10s

keys: ./config/keys_real_test.json

storage:
  path: './.local_data/database'
  engine:
    type: rocks_db

prometheus:
  push_gateway: 127.0.0.1:9091
  instance: balance_reporter

api:
  port: 0
