exchanges:
  binance:
    fees: 0.001
    use_account: true
    use_margin_account: true
    use_test: true
    orderbook_depth: 5
    orderbook:
      symbols: [ 'BURGER_USDT' ]

streams:
  - type: ExchangeBots

outputs:
  - type: Strategies

strategies:
  driver:
    type: generic
    dry_mode: true
    start_trading: false
    portfolio:
      initial_quote_cash: 100.0
      fees_rate: 0.001
    strat:
      type: mean_reverting
      pair: ''
      short_window_size: 100
      long_window_size: 1000
      sample_freq: 1min
      threshold_short: 0.01
      threshold_long: -0.01
      threshold_eval_freq: 1
      dynamic_threshold: true
      threshold_window_size: 1000
      stop_loss: -0.1
      stop_gain: 0.075
      exchange: Binance
      order_conf:
        order_mode: limit
        dry_mode: true
        asset_type: spot

keys: ./config/keys_real_test.json

storage:
  path: .local_data/strat_backtest_dbs
  engine:
    type: rocks_db

prometheus:
  push_gateway: 127.0.0.1:9091
  instance: trader

api:
  port: 8188
  allowed_origins:
    - "http://localhost:3001"
