
exchanges:
#  Bitstamp:
#    orderbook:
#      symbols: ['BTC_USD']
#      trades:
#        symbols: ['BTC_USD']
  bittrex:
    orderbook:
      symbols: ['BTC_USD']
    trades:
      symbols: ['BTC_USD']

file_rotation:
  max_file_size: 50 Mb
  max_file_time: 1800

data_dir: "./data"

keys: keys_real.json
