---

exchanges:
  binance:
    orderbook:
      symbols: ['BTC_USDT', 'ETH_USDT']

strategies:
  - type: Naive
    left: 'ETH_USDT'
    right: 'BTC_USDT'
    exchange: Binance

file_rotation:
  max_file_size: 1 Mb
  max_file_time: 10

data_dir: './data'

keys: keys_real.json
