---

exchanges:
  binance:
    fees: 0.001
    orderbook:
      symbols: ['BTC_USDT']
    trades:
      symbols: ['BTC_USDT']

strategies:
  - type: Naive
    left: 'ETH_USDT'
    right: 'BTC_USDT'
    exchange: Binance
    beta_eval_freq: 5000
    beta_sample_freq: 1min
    window_size: 500
    threshold_long: -0.04
    threshold_short: 0.04
    stop_loss: -0.1
    stop_gain: 0.075

file_rotation:
  max_file_size: 1 Mb
  max_file_time: 10

data_dir: './data'

keys: keys_real.json

db_storage_path: './data'

prom_push_gw: 127.0.0.1:9091
