
exchanges:
#  Bitstamp:
#    orderbook:
#      symbols: ['BTC_USD']
#      trades:
#        symbols: ['BTC_USD']

  bittrex:
    orderbook:
      symbols: ['BTC_USDT', 'ETH_USDT', 'ETC_USDT', 'BTC_USD', 'ETH_USD', 'BSV_USD', 'USDT_USD', 'XRP_USD', 'LTC_USD', 'ETH_BTC', 'BCH_BTC', 'ETC_BTC', 'BSV_BTC', 'XTP_BTC', 'XRP_BTC', 'ADA_BTC', 'TUSD_BTC', 'STEEM_BTC', 'LTC_BTC', 'ZEC_BTC']
    trades:
      symbols: ['BTC_USDT', 'ETH_USDT', 'ETC_USDT', 'BTC_USD', 'ETH_USD', 'BSV_USD', 'USDT_USD', 'XRP_USD', 'LTC_USD', 'ETH_BTC', 'BCH_BTC', 'ETC_BTC', 'BSV_BTC', 'XTP_BTC', 'XRP_BTC', 'ADA_BTC', 'TUSD_BTC', 'STEEM_BTC', 'LTC_BTC', 'ZEC_BTC']
  binance:
    orderbook:
      symbols: ['BTC_USDT', 'BCH_USDT', 'ETH_USDT', 'ETC_USDT', 'XRP_USDT', 'EOS_USDT', 'BNB_USDT', 'LTC_USDT', 'DASH_USDT', 'BAB_USD', 'ETC_USD', 'BTC_USD', 'ETH_USD', 'BSV_USD', 'USDT_USD', 'XRP_USD', 'LTC_USD', 'EOS_USD', 'ETH_BTC', 'BCH_BTC', 'ETC_BTC', 'XRP_BTC', 'BSV_BTC', 'XTP_BTC', 'XRP_BTC', 'ADA_BTC', 'TUSD_BTC', 'STEEM_BTC', 'LTC_BTC', 'ZEC_BTC', 'BTC_EUR', 'ETH_EUR']
    trades:
      symbols: ['BTC_USDT', 'BCH_USDT', 'ETH_USDT', 'ETC_USDT', 'XRP_USDT', 'EOS_USDT', 'BNB_USDT', 'LTC_USDT', 'DASH_USDT', 'BAB_USD', 'ETC_USD', 'BTC_USD', 'ETH_USD', 'BSV_USD', 'USDT_USD', 'XRP_USD', 'LTC_USD', 'EOS_USD', 'ETH_BTC', 'BCH_BTC', 'ETC_BTC', 'XRP_BTC', 'BSV_BTC', 'XTP_BTC', 'XRP_BTC', 'ADA_BTC', 'TUSD_BTC', 'STEEM_BTC', 'LTC_BTC', 'ZEC_BTC', 'BTC_EUR', 'ETH_EUR']

file_rotation:
  max_file_size: 50 Mb
  max_file_time: 1800

data_dir: './data'

keys: keys_real.json
