---

exchanges:
  binance:
    orderbook:
      symbols: ['BTC_USDT', 'ETH_USDT']
    trades:
      symbols: ['BTC_USDT', 'ETH_USDT']

strategies:
  - type: Naive
    left: 'ETH_USDT'
    right: 'BTC_USDT'
    exchange: Binance
    beta_eval_freq: 5000
    beta_sample_freq: 1min
    window_size: 500


file_rotation:
  max_file_size: 1 Mb
  max_file_time: 10

data_dir: './data'

keys: keys_real.json

db_storage_path: './data'

prom_push_gw: 127.0.0.1:9091
