exchanges:
  binance:
    use_account: false
    use_test: false
    fees: 0.001
    orderbook_depth: 5
    orderbook:
      symbols: ['.*_USDT']
      #symbols: ['BTC_USDT', 'ETH_USDT']
    trades:
      symbols: ['.*_USDT']

streams:
  - type: ExchangeBots

outputs:
  - type: Nats
    username: ruser
    password: T0pS3cr3t
    host: localhost:4222

keys: ./config/keys_real_test.json

db_storage_path: './database'

prometheus:
  push_gateway: 127.0.0.1:9091
  instance: feeder

api:
  port: 0
