exchanges:
  #  Bitstamp:
  #    orderbook:
  #      symbols: ['BTC_USD']
  #      trades:
  #        symbols: ['BTC_USD']
  binance:
    use_account: false
    use_test: false
    fees: 0.001
    orderbook_depth: 5
    orderbook:
      #symbols: ['.*_USDT']
      symbols: ['BTC_USDT', 'ETH_USDT']
#    trades:
#      symbols: ['BTC_USDT', 'BCH_USDT', 'ETH_USDT', 'ETC_USDT', 'XRP_USDT', 'EOS_USDT', 'BNB_USDT', 'LTC_USDT', 'DASH_USDT', 'ETH_BTC', 'BCH_BTC', 'ETC_BTC', 'ADA_BTC', 'BTC_TUSD', 'STEEM_BTC', 'LTC_BTC', 'ZEC_BTC', 'BTC_EUR', 'ETH_EUR']

streams:
  - type: ExchangeBots

outputs:
  - type: Nats
    username: ruser
    password: T0pS3cr3t
    host: localhost:4222

data_dir: './data'

keys: ./config/keys_real_test.json

db_storage_path: './database'

prom_push_gw: 127.0.0.1:9091

prom_instance: feeder

api:
  port: 8180
