streams:
  - type: Nats
    username: ruser
    password: T0pS3cr3t
    host: localhost:4222

outputs:
  - type: AvroFileLogger
    file_rotation:
      max_file_size: 50 Mb
      max_file_time: 1800
    basedir: './data'
    partitions_grace_period: 1s

data_dir: './data'

keys: ./config/keys_real_test.json

db_storage_path: './database'

prometheus:
  push_gateway: 127.0.0.1:9091
  instance: logger


api:
  port: 8181
