streams:
  - type: Nats
    username: ruser
    password: T0pS3cr3t
    host: localhost:4222

outputs:
  - type: AvroFileLogger
    file_rotation:
      max_file_size: 1 Mb
      max_file_time: 60
    basedir: './data'
    partitions_grace_period: 1s

keys: ./config/keys_real_test.json

storage:
  path: './.local_data/database'
  engine:
    type: rocks_db

prometheus:
  push_gateway: 127.0.0.1:9091
  instance: logger


api:
  port: 0
