exchanges:
  binance:
    use_account: true
    use_test: true
    fees: 0.001
    orderbook:
      symbols: ['BTC_USDT']

streams:
  - type: Nats
    username: ruser
    password: T0pS3cr3t
    host: localhost:4222

outputs:
  - type: Strategies

strategies:
  - type: mean_reverting
    pair: 'BTC_USDT'
    short_window_size: 100
    long_window_size: 1000
    dry_mode: false
    sample_freq: 1min
    initial_cap: 100.0
    threshold_short: 0.01
    threshold_long: -0.01
    threshold_eval_freq: 1
    dynamic_threshold: true
    threshold_window_size: 10000
    stop_loss: -0.1
    stop_gain: 0.075
    exchange: Binance
    order_mode: market

data_dir: './data'

keys: ./config/keys_real_test.json

db_storage_path: './database'

prometheus:
  push_gateway: 127.0.0.1:9091
  instance: trader

api:
  port: 8182
  cors: permissive
