exchanges:
  #  Bitstamp:
  #    orderbook:
  #      symbols: ['BTC_USD']
  #      trades:
  #        symbols: ['BTC_USD']
  binance:
    use_account: false
    use_test: true
    fees: 0.001
    orderbook:
      symbols: ['BTC_USDT', 'ETH_USDT']
#    trades:
#      symbols: ['BTC_USDT', 'BCH_USDT', 'ETH_USDT', 'ETC_USDT', 'XRP_USDT', 'EOS_USDT', 'BNB_USDT', 'LTC_USDT', 'DASH_USDT', 'ETH_BTC', 'BCH_BTC', 'ETC_BTC', 'ADA_BTC', 'BTC_TUSD', 'STEEM_BTC', 'LTC_BTC', 'ZEC_BTC', 'BTC_EUR', 'ETH_EUR']

streams:
  - type: Nats
    username: ruser
    password: T0pS3cr3t
    host: localhost:4222

outputs:
  - type: AvroFileLogger
    file_rotation:
      max_file_size: 50 Mb
      max_file_time: 1800
    basedir: './data'
  - type: Strategies

strategies:
  - type: Naive
    left: 'BCH_USDT'
    right: 'ETC_USDT'
    exchange: Binance
    beta_eval_freq: 5000
    beta_sample_freq: 10secs
    window_size: 500
    threshold_long: -0.02
    threshold_short: 0.02
    stop_loss: -0.1
    stop_gain: 0.075
    initial_cap: 20.0

data_dir: './data'

keys: ./config/keys_real_test.json

db_storage_path: './database'

prom_push_gw: 127.0.0.1:9091

prom_instance: trader

api:
  port: 8180
