# reference implementation

exchanges:
  binance:
    orderbook:
      symbols: ['BTC_USDT', 'ETH_USDT']
    trades:
      symbols: ['BTC_USDT', 'ETH_USDT']
    use_test: true
strategies:
  - type: naive
    left: 'ETH_USDT'
    right: 'BTC_USDT'
    exchange: Binance

file_rotation:
  max_file_size: 50 Mb
  max_file_time: 1800

data_dir: './data_test'

keys: keys_test.json
