#strats: []
strats:
  - driver:
      type: generic
      portfolio:
        initial_quote_cash: 1000.0
        fees_rate: 0.001
    strat:
      type: 'stoch_rsi'
      pair: 'ETH_USDT'
      exchange: 'binance'
      resolution:
        time_unit: 'minute'
        units: 15
      tick_rate: 1s
      stop_loss: -0.06
      trailing_stop_start: 0.01
      trailing_stop_loss: 0.01
      security_type: 'future'
      source: 'close'
      order_conf:
        order_mode: limit
        dry_mode: true
        asset_type: usdt_margined_futures

fees: 0.0004

period:
  type: interval
  from: 2022-03-02T00:00:00
  to: 2022-03-15T00:00:00

db_path: /media/ramdisk/strat_backtest_dbs

db_conf:
  type: in_memory

use_generic: false

output_dir: ./target/backtests_results

report:
  parallelism: 2
  compression:
    algorithm: gz
    level: 5

report_sample_rate: 1s
