#strats: []
strats:
  - driver:
      type: generic
      portfolio:
        initial_quote_cash: 100.0
        fees_rate: 0.001
    strat:
      type: kline_logger
      key: 'kline_logger_BTC_USDT_rust'
      pair: 'BTC_USDT'

fees: 0.001

period:
  type: interval
  from: 2022-01-01
  to: 2022-02-07

input_format: parquet
input_dataset: trades
input_sample_rate: 1min

db_path: /media/ramdisk/strat_backtest_dbs

db_conf:
  type: in_memory

use_generic: false

output_dir: ./target/backtests_results

report:
  parallelism: 2
  compression:
    algorithm: gz
    level: 5

