[package]
name = "python_dylib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"
name = "strategy"

[package.metadata.maturin]
name = "strategy"
python-source = "python_src"

[dependencies]
strategy_python = { path = "../strategy_python", features = ["static"] }

pyo3 = { version = "^0.15", features = ["serde", "auto-initialize", "extension-module"] }
pyo3-log = { version = "0.5"}
log = "0.4"

[patch.crates-io]
plotly = { git = "https://github.com/igiagkiozis/plotly", branch = "master" }
actix-cors = { git = "https://github.com/actix/actix-extras", branch = "master" }
pyo3 = { git = "https://github.com/PyO3/pyo3", rev = "8a989eeb6aeb862c0c518d994ef6e5f967f0dc46", version = "^0.15" }
pythonize = { git = "https://github.com/Igosuki/pythonize", rev = "d5309ca6491cdfb9e356d38b244e20b29a206bbc", version = "^0.15" }
