[package]
name = "account"
version = "0.1.0"
authors = ["Guillaume Balaine <igosuki@gmail.com>"]
edition = "2021"

[lib]
name = "portfolio"
path = "src/lib.rs"

[dependencies]
#coinnect_rt = { git = " ssh://git@github.com/Igosuki/coinnect_rt.git" }
coinnect_rt = { path = "../coinnect" }
trading = { path = "../trading" }
util = { path = "../util" }
db = { path = "../db" }
# actix
actix = "0.12"
actix_derive = "0.6"

# metrics
prometheus = "0.12"
tracing = { version = "0.1", features = ["release_max_level_debug", "log"] }

# std
thiserror = "1.0"
serde = "1.0"
anyhow = "1.0"
chrono = "0.4"

# async
futures = "0.3"
async-trait = "0.1"

[dev-dependencies]
