[package]
name = "portfolio"
version = "0.1.0"
authors = ["Guillaume Balaine <igosuki@gmail.com>"]
edition = "2018"

[lib]
name = "portfolio"
path = "src/lib.rs"

[dependencies]
# Crypto
#coinnect_rt = { git = " ssh://git@github.com/Igosuki/coinnect_rt.git" }
coinnect_rt = { path = "../coinnect" }
# actix
actix = "0.11"
actix-rt = "2.2"
actix_derive = "0.6"

thiserror = "1.0"
anyhow = "1.0"

[dev-dependencies]
