[target.x86_64-unknown-linux-gnu]
#linker="clang"
## debug
rustflags = [
    "-Clink-arg=-fuse-ld=lld", "-Clink-arg=-Wl,--no-rosegment", "--cfg", "tokio_unstable", "-g", "-Cforce-frame-pointers=y"
]
[env]
#BZIP2_LIB_DIR="/usr/lib/x86_64-linux-gnu/"
#ZSTD_LIB_DIR="/usr/lib/x86_64-linux-gnu/"
#ROCKSDB_LIB_DIR="/usr/local/lib/"
[build]
## debug
rustflags = ["--cfg", "tokio_unstable", "-g", "-Cforce-frame-pointers=y"]
target-dir = "target"
