cargo-features = ["edition2021"]

[package]
name = "metrics"
version = "0.1.0"
authors = ["Guillaume Balaine <igosuki@gmail.com>"]
edition = "2018"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prometheus = "0.12"
actix = "0.12"
awc = "3.0.0-beta.5"
thiserror = "1.0"
lazy_static = "1.4"
log = "0.4"
serde = "1.0"
libc = "0.2"
actix-http = "3.0.0-beta.6"
protobuf = "2.12"
tokio = "1.9"

[dev-dependencies]
